image: alpine

pages:
  script:
  - apk update && apk add doxygen
  - cd doc
  - doxygen Doxyfile
  - cd ..
  - mkdir public
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
