stages:
- deploy

pages:
  image: registry.gitlab.com/antoniocoratelli/docker-builder-as-a-service/doxygen
  stage: deploy
  script:
  - cd doc; doxygen Doxyfile; cd ..
  - mv doc/html public
  artifacts:
    paths:
    - public
  only:
  - master
