dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - mkdir build
  - cd build
  - cmake ..
  - make
